carpenpi/getR.py

Download if file does not exists and remove regex pattern argument

Check if file exists and remove regex argument

---

.gitignore
carpenpi/cli.py
carpenpi/main.py

Add pypi mirror

---

offlinedatasci/miniCran.R

Check for updates, prevent download

---

offlinedatasci/main.py

This includes two downloads instead of one.

Download R for mac using new link structure

---

offlinedatasci/main.py

Add Library Carpentry lessons

---

test/test_offlinedatasci.py

This makes it easier to test within the repo without creating a lot of extra files.

Switch to using temp path for testing

---

offlinedatasci/main.py

* Single lesson directory
* Named directories for each lesson sourc

Restructure lesson storage

---

.github/workflows/package-check.yml
offlinedatasci/main.py
pyproject.toml

Add running test suite to GH Actions checks

---

docs/installation.md

Have docs install correct package

---

offlinedatasci/main.py
offlinedatasci/miniCran.R
test/test_offlinedatasci.py

Use current R version for miniCRAN repo

---

docs/getting-started.md
offlinedatasci/cli.py
offlinedatasci/main.py

This had been only handled in the CLI. Adding this also simplifies code in several places by removing the need to loop over multiple functions.
Also a small docs fix

Add download_all functionality to Python interface

---

offlinedatasci/main.py
test/test_offlinedatasci.py

Co-authored-by:  Abhishek Dasgupta <abhidg@trenozoic.net>
Fixes #96

Add test for download_python_libraries

---

paper.bib
paper.md

Minor edits to paper

---

offlinedatasci/cli.py
offlinedatasci/main.py
test/test_offlinedatasci.py

- install python_libraries -> install python-packages
- install minicran -> install r-packages
- add-packages r package1 -> add r-packages package1
- add-packages python package1 -> add python-packages package1
Closes #92

Updating API to be more intuitive 

---

.github/workflows/package-check.yml
offlinedatasci/miniCran.R
test/test_offlinedatasci.py

Switch to the newly released version of miniCRAN and implement automated testing of CRAN mirror setup.

R package fixes

---

README.md

Displays the number of monthly downloads from PyPI

Add a PyPI downloads badge

---

docs/getting-started.md

Update docs to reflect API changes

---

paper.bib
paper.md

Added most of the packages that were used to the references. Since some are not explicitly mentioned I did not include them in the text. Wondering how to approach this. Maybe a: "Not mentioned in the text but used for x, y, z” section?

Adding some software references

---

paper.bib
paper.md

Misc edits on a read-through + updating R citation.

Edits from Heather

---

README.md
docs/getting-started.md

Also include a minor restructuring of install instructions to put pipx near the top.
Closes #124

Add pipx installation instructions
